# Generated by Django 3.2.7 on 2021-09-17 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 18, 1, 5, 26, 994111)),
        ),
    ]
