# Generated by Django 3.2.7 on 2021-09-17 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 18, 1, 7, 50, 317255)),
        ),
    ]
